[keyboard]
name = "ZX66 RMK Keyboard"
product_name = "ZX66 Keyboard"
vendor_id = 0xFEED
product_id = 0x9527
manufacturer = "Zongxin"
chip = "nrf52840"
usb_enable = true

[split]
connection = "ble"

[storage]
enabled = true
clear_storage = true


[layout]
rows = 5
cols = 15
layers = 4
keymap = [
    [
        ["Escape",    "Kc1",  "Kc2",    "Kc3",   "Kc4",   "Kc5",    "Kc6",      "No",   "Kc7",   "Kc8",   "Kc9",     "Kc0",       "Minus",        "Equal",         "Backspace" ],
        ["Tab",       "Q",    "W",      "E",     "R",     "T",      "Y",        "No",   "U",     "I",     "O",       "P",         "LeftBracket",  "RightBracket",  "Backslash" ],
        ["CapsLock",  "A",    "S",      "D",     "F",     "G",      "No",       "H",    "J",     "K",     "L",       "Semicolon", "Quote",        "Enter",         "No"        ],
        ["LShift",    "Z",    "X",      "C",     "V",     "B",      "No",       "N",    "M",     "Comma", "Dot",     "Slash",     "RShift",       "Up",            "MO(3)"     ],
        ["LCtrl",     "LGui", "MO(1)",  "LAlt",  "No",    "Space",  "No",       "No",   "MO(2)", "No",    "PageUp",  "Home",      "Left",         "Down",          "Right"     ],    
    ],

    [
        ["Delete",    "F1",   "F2",    "F3",    "F4",    "F5",      "F6",       "No",  "F7",    "F8",             "F9",             "F10",             "F11",            "F12",           "Delete"],
        ["Tab",       "_",    "_",     "_",     "_",     "_",       "_",        "No",  "_",     "_",              "_",              "_",               "AudioVolUp",     "AudioVolDown",  "AudioMute"],
        ["CapsLock",  "_",    "_",     "_",     "_",     "_",       "No",       "_",   "_",     "_",              "_",              "BrightnessUp",    "BrightnessDown", "Enter",         "No"],
        ["LShift",    "_",    "_",     "_",     "_",     "_",       "No",       "_",   "_",     "MediaPrevTrack", "MediaNextTrack", "MediaPlayPause",  "RShift",         "Up",            "MO(3)"],
        ["LCtrl",     "LGui", "MO(1)", "LAlt",  "No",    "Space",   "No",       "No",  "MO(2)", "No",             "PageDown",       "End",             "Left",           "Down",          "Right"],      
    ],

    [
        ["Grave",     "_",    "_",     "_",     "_",     "_",       "_",        "No",  "_",     "_",   "_",     "_",    "_",       "_",      "_"    ],
        ["Tab",       "_",    "_",     "_",     "_",     "_",       "_",        "No",  "_",     "_",   "_",     "_",    "_",       "_",      "_"    ],
        ["CapsLock",  "_",    "_",     "_",     "_",     "_",       "No",       "_",   "_",     "_",   "_",     "_",    "_",       "Enter",  "No"   ],
        ["LShift",    "_",    "_",     "_",     "_",     "_",       "No",       "_",   "_",     "_",   "_",     "_",    "RShift",  "Up",     "MO(3)"],
        ["LCtrl",     "LGui", "MO(1)", "LAlt",  "No",    "Space",   "No",       "No",  "MO(2)", "No",  "_",     "_",    "Left",    "Down",   "Right"],      
    ],

    [
        ["Escape",    "User0","User1", "User2", "User3", "User4",   "User5",    "No",  "_",      "_",  "_",  "_",   "_",       "_",       "_"],
        ["Tab",       "_",    "_",     "_",     "_",     "_",       "_",        "No",  "_",      "_",  "_",  "_",   "_",       "_",       "_"],
        ["CapsLock",  "_",    "_",     "_",     "_",     "_",       "No",       "_",   "_",      "_",  "_",  "_",   "_",       "Enter",   "No"],
        ["LShift",    "_",    "_",     "_",     "_",     "_",       "No",       "_",   "_",      "_",  "_",  "_",   "RShift",  "Up",      "MO(3)"],
        ["LCtrl",     "LGui", "MO(1)", "LAlt",  "No",    "Space",   "No",       "No",  "MO(2)",  "No", "_",  "_",   "Left",    "Down",    "Right"],      
    ],
]


[split.central]
rows = 5
cols = 7
row_offset = 0
col_offset = 0

[split.central.matrix]
matrix_type = "normal"
row_pins = ["P0_10", "P1_06", "P0_09", "P1_04", "P0_02"]
col_pins = ["P1_13", "P1_02", "P1_10","P0_29", "P0_31","P0_30","P0_05"]

[[split.peripheral]]
rows = 5
cols = 8
row_offset = 0
col_offset = 7

[split.peripheral.matrix]
matrix_type = "normal"
row_pins = ["P0_10", "P1_06", "P0_09", "P1_04", "P0_02"]
col_pins = ["P1_13", "P1_02", "P1_10","P0_29", "P0_31","P0_30","P0_05","P1_09"]

[ble]
enabled = true
#battery_adc_pin = "vddh"
battery_adc_pin = "P0_28"
adc_divider_measured = 2000
adc_divider_total = 2806
charge_state.pin = "P1_11"
charge_state.low_active = false

[host]
vial_enabled = true
unlock_keys = [[0, 0], [0, 1]]

[aliases]
my_cut = "WM(X, LCtrl)"
my_copy = "WM(C, LCtrl)"
my_paste = "WM(V, LCtrl)"